### ISSUE TITLE
Another potential stack issue: clx may be incorrectly implemented

### ISSUE THREAD

**Issue by acser123** [isene/xrpn#10]
This program works on the iOS i41CX+ emulator. 
(The FOCAL program is from http://hp41programs.yolasite.com/roman.php )
E2 is synthetic for 100
E3 is synthetic for 1000, both replaced in the below code.

$ cat ar3.hp41
LBL "A-R"
CLA
LBL 01
1000
X>Y?
GTO 00
-
"|-M"
GTO 01
LBL 00
CLX
900
X<=Y?
"|-CM"
X>Y?
CLX
-
500
X<=Y?
"|-D"
X>Y?
CLX
-
400
X<=Y?
"|-CD"
X>Y?
CLX
-
LBL 02
100
X>Y?
GTO 00
-
"|-C"
GTO 02
LBL 00
CLX
90
X<=Y?
"|-XC"
X>Y?
CLX
-
50
X<=Y?
"|-L"
X>Y?
CLX
-
40
X<=Y?
"|-XL"
X>Y?
CLX
-
LBL 03
10
X>Y?
GTO 00
-
"|-X"
GTO 03
LBL 00
DSE X
X<=Y?
"|-IX"
X>Y?
CLX
-
5
X<=Y?
"|-V"
X>Y?
CLX
-
4
X<=Y?
"|-IV"
X>Y?
CLX
-
LBL 04
1
X>Y?
GTO 00
-
"|-I"
GTO 04
LBL 00
AVIEW
END
$ 

$ xrpn -l ar3.hp41
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> page 1
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> l
Line 1: lbl "A-R"
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> 1000 
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 1,000.0000   L = 0.0000
> s
Line 2: cla

------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 1,000.0000   L = 0.0000
> s
Line 3: lbl 01
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 1,000.0000   L = 0.0000
> s
Line 4: 0
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 1,000.0000
X = 0.0000   L = 1,000.0000
> s
Line 5: xgty?
NO
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 1,000.0000
X = 0.0000   L = 1,000.0000
> s
Line 6: gto 00
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 1,000.0000
X = 0.0000   L = 1,000.0000
> s
Line 11: clx
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 1,000.0000
X = 0.0000   L = 1,000.0000
> s
Line 12: 
Traceback (most recent call last):
/home/acser/bin/xrpn:55:in `<main>': undefined method `downcase' for nil:NilClass (NoMethodError)
$ 
$

**Comment by isene** [comment]
I cannot reproduce the error. What I see is that the program loops indefinitely, though. I can single-step until I get blue in my face... but no error like the one you report (and I simply did a copy-paste of the listing above, loaded with the -l switch, did `page 1`and started single-stepping with `s`.

**Comment by acser123** [comment]
I will recheck the code in the meantime.

**Comment by isene** [comment]
I did, however discover one thing that must be fixed: Single-stepping conditionals treats those lines as though they are entered manually and only reports "YES" or "NO" and do not advance the program counter appropriately.

**Comment by isene** [comment]
Latest update now treats conditionals correctly.

**Comment by acser123** [comment]
Great, thanks. Let me recheck the code, it is likely a user (programming) error that arose from regex replacements in vim to massage the listing from HTML to XRPN plain text code. See EOU #4

**Comment by acser123** [comment]
I think I got it.
Line 4 works just fine.

However, line 12 puts the number 900 on the stack. However, it shifts the stack up. This is not the HP 41 behavior. When you type a number and do not press the <Enter^> key on the HP 41, it places the number into X. From this point, it's all broken and results in the infinite loop. I think you have to implement typing a number and not pressing <Enter^> but still placing that number onto the stack. Also, you may want to look into the 'clx' command code as that precedes the offending line 12 but not line 4.

$ cat ar4.hp41 
LBL "A-R"
" "
LBL 01
1000
X>Y?
GTO 00
-
"|-M"
GTO 01
LBL 00
CLX
900
X<=Y?
"|-CM"
X>Y?
CLX
-
500
X<=Y?
"|-D"
X>Y?
CLX
-
400
X<=Y?
"|-CD"
X>Y?
CLX
-
LBL 02
100
X>Y?
GTO 00
-
"|-C"
GTO 02
LBL 00
CLX
90
X<=Y?
"|-XC"
X>Y?
CLX
-
50
X<=Y?
"|-L"
X>Y?
CLX
-
40
X<=Y?
"|-XL"
X>Y?
CLX
-
LBL 03
10
X>Y?
GTO 00
-
"|-X"
GTO 03
LBL 00
DSE X
X<=Y?
"|-IX"
X>Y?
CLX
-
5
X<=Y?
"|-V"
X>Y?
CLX
-
4
X<=Y?
"|-IV"
X>Y?
CLX
-
LBL 04
1
X>Y?
GTO 00
-
"|-I"
GTO 04
LBL 00
AVIEW
END
$ 



$ xrpn -l ar4.hp41 
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> 14
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 14.0000   L = 0.0000
> l
Line 1: lbl "XRPN"
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 14.0000   L = 0.0000
> page 1
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 14.0000   L = 0.0000
> l
Line 1: lbl "A-R"
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 14.0000   L = 0.0000
> s
Line 2: " "
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 0.0000
X = 14.0000   L = 0.0000
> s
Line 3: lbl 01
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 0.0000
X = 14.0000   L = 0.0000
> s
Line 4: 1000
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 14.0000
X = 1,000.0000   L = 14.0000
> s
Line 5: xgty?
YES
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 14.0000
X = 1,000.0000   L = 14.0000
> s
Line 6: gto 00
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 14.0000
X = 1,000.0000   L = 14.0000
> s
Line 11: clx
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 14.0000
X = 0.0000   L = 14.0000
> s
Line 12: 900
------------------------------
T = 0.0000   α =  
Z = 14.0000
Y = 0.0000
X = 900.0000   L = 0.0000
>

**Comment by acser123** [comment]
I was able to reduce the problem to a much simpler example:
$ cat test2.hp41 
lbl "TEST2"
1
2
3
4
clx
5
end
$ xrpn -f test2.hp41
------------------------------
T = 2.0000   α = 
Z = 3.0000
Y = 0.0000
X = 5.0000   L = 0.0000
> 
The correct stack should not have Y=0. It should be X=5, Y=4, Z=3, T=2.

**Comment by isene** [comment]
Check latest (implemented stack lift disabling, something that is triggered with CLX)

We can't have numbers entered without pressing Enter as there is no way to know how many digits the user will want to enter - unless we also implement time travel.

**Comment by isene** [comment]
Also implemented the E2, E3, etc mnemonics

**Comment by acser123** [comment]
E2 and E3 worked but putting 1000 on the stack still intermittently fails.

**Comment by isene** [comment]
"putting 1000 on the stack still intermittently fails"

How?

**Comment by isene** [comment]
"putting 1000 on the stack still intermittently fails"

How?

**Comment by isene** [comment]
"putting 1000 on the stack still intermittently fails"

How?

**Comment by acser123** [comment]
It shows up as 0. Check the listing.
    On Saturday, April 9, 2022, 11:08:27 AM EDT, Geir Isene ***@***.***> wrote:  
 
 


"putting 1000 on the stack still intermittently fails"

How?
