### ISSUE TITLE
R/S button implementation is ambiguous

### ISSUE THREAD

**Issue by acser123** [isene/xrpn#12]
When a program gets to a STOP, execution stops. At this time you can continue by hitting the enter key ion the keyboard. This is not consistent with the calculator's operation. 

There should be a R/S or R_S or RUNSTOP command that mimics the "R/S" key on the HP 41. Using the <Enter> key is not good as it should duplicate X to Y and leave X in X.

Debugging should be completely separate from the R/S button.

**Comment by isene** [comment]
Since the goal of XRPN is not to emulate an HP-41 properly (only FOCAL programs), I would rather not do this. It is simpler and cleaner the way it functions now (and more intuitive for people not intimately familiar with the calculator)
