### ISSUE TITLE
Placing a number on the stack intermittently fails in a program

### ISSUE THREAD

**Issue by acser123** [isene/xrpn#14]
$ cat ar4.hp41
LBL "A-R"
" "
LBL 01
1000
X>Y?
GTO 00
-
"|-M"
GTO 01
LBL 00
drop
900
X<=Y?
"|-CM"
X>Y?
CLX
-
500
X<=Y?
"|-D"
X>Y?
CLX
-
400
X<=Y?
"|-CD"
X>Y?
CLX
-
LBL 02
100
X>Y?
GTO 00
-
"|-C"
GTO 02
LBL 00
clx
90
X<=Y?
"|-XC"
X>Y?
CLX
-
50
X<=Y?
"|-L"
X>Y?
CLX
-
40
X<=Y?
"|-XL"
X>Y?
CLX
-
LBL 03
10
X>Y?
GTO 00
-
"|-X"
GTO 03
LBL 00
DSE X
X<=Y?
"|-IX"
X>Y?
CLX
-
5
X<=Y?
"|-V"
X>Y?
CLX
-
4
X<=Y?
"|-IV"
X>Y?
CLX
-
LBL 04
1
X>Y?
GTO 00
-
"|-I"
GTO 04
LBL 00
AVIEW
END
$ 

$ xrpn -l ar4.hp41 
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> page 1
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> 144
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 144.0000   L = 0.0000
> l
Line 1: lbl "A-R"
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 144.0000   L = 0.0000
> s
Line 2: " "
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 0.0000
X = 144.0000   L = 0.0000
> s
Line 3: lbl 01
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 0.0000
X = 144.0000   L = 0.0000
> s
Line 4: 0 <<<<<<-------------- this is the problem. This should be 1000. This issue only happens intermittently.
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 144.0000
X = 0.0000   L = 144.0000

**Comment by isene** [comment]
iI believe this is the result of the GTO issue (#15)

**Comment by acser123** [comment]
This issue is still not fixed.
 The code is the same: the first code listing on http://hp41programs.yolasite.com/roman.php

$ xrpn -l ar4.hp41 
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> l       
Line 1: lbl "XRPN"
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> page 1
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> l   
Line 1: lbl "A-R"
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> 14
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 14.0000   L = 0.0000
> s
Line 2: " "
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 0.0000
X = 14.0000   L = 0.0000
> s
Line 3: lbl 01
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 0.0000
X = 14.0000   L = 0.0000
> s
Line 4: 1e3
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 14.0000
X = 1,000.0000   L = 14.0000
> s
Line 5: xgty?
YES
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 14.0000
X = 1,000.0000   L = 14.0000
> s
Line 6: gto 00
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 14.0000
X = 1,000.0000   L = 14.0000
> s
Line 11: clx
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 14.0000
X = 0.0000   L = 14.0000
> s
Line 12: 
Traceback (most recent call last):
/home/acser/bin/xrpn:57:in `<main>': undefined method `downcase' for nil:NilClass (NoMethodError)
$
