### ISSUE TITLE
Programs without a last END instruction should not cause a stack error

### ISSUE THREAD

**Issue by acser123** [isene/xrpn#19]
> s
Line 201: 
Traceback (most recent call last):
/home/acser/bin/xrpn:42:in `<main>': undefined method `match' for nil:NilClass (NoMethodError)
$

**Comment by isene** [comment]
The following program simply terminates when there's no END:

```
LBL "TERM"
"puts 'TERMINATE'"
RUBYCMD
```

Could you provide the rest of the code so that I can reproduce?

**Comment by acser123** [comment]
$ xrpn -l noend.hp41
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> page 1
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> l
Line 1: lbl "NOEND"
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> s
Line 2: 1
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 1.0000   L = 0.0000
> s
Line 3: 2
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 1.0000
X = 2.0000   L = 1.0000
> s
Line 4: 3
------------------------------
T = 0.0000   α = 
Z = 1.0000
Y = 2.0000
X = 3.0000   L = 2.0000
> s
Line 5: 4
------------------------------
T = 1.0000   α = 
Z = 2.0000
Y = 3.0000
X = 4.0000   L = 3.0000
> s
Line 6: 
Traceback (most recent call last):
/home/acser/bin/xrpn:42:in `<main>': undefined method `match' for nil:NilClass (NoMethodError)
$ ^C
$ 
$ xrpn -l noend.hp41
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> page 1
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> pprgx
01◆lbl "NOEND"
02 1
03 2
04 3
05 4
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
>

**Comment by acser123** [comment]
I believe that the HP 41 automatically inserts and .END. instruction in these cases.

**Comment by isene** [comment]
The issue only happens when you single-step a program to the end where there is no END - so this only happens in "Debug Mode". I therefore added an END instruction only when in Debug Mode and single-stepping to a non-existing END. I deliberately didn't add an END to a program without an END as it should be possible to run such a program and let it terminate without an END.
