### ISSUE TITLE
Placing a number on the stack from a program crashes (same code as in #14)

### ISSUE THREAD

**Issue by acser123** [isene/xrpn#20]
Looks like issue #14 is still not fixed.

http://hp41programs.yolasite.com/roman.php first example is the code, it's the same as in #14  Now the crash happens after clx, when the code tries to place 900 on the stack.

$ xrpn -l ar4.hp41 
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> l       
Line 1: lbl "XRPN"
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> page 1
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> l   
Line 1: lbl "A-R"
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> 14
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 14.0000   L = 0.0000
> s
Line 2: " "
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 0.0000
X = 14.0000   L = 0.0000
> s
Line 3: lbl 01
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 0.0000
X = 14.0000   L = 0.0000
> s
Line 4: 1e3
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 14.0000
X = 1,000.0000   L = 14.0000
> s
Line 5: xgty?
YES
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 14.0000
X = 1,000.0000   L = 14.0000
> s
Line 6: gto 00
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 14.0000
X = 1,000.0000   L = 14.0000
> s
Line 11: clx
------------------------------
T = 0.0000   α =  
Z = 0.0000
Y = 14.0000
X = 0.0000   L = 14.0000
> s
Line 12: 
Traceback (most recent call last):
/home/acser/bin/xrpn:57:in `<main>': undefined method `downcase' for nil:NilClass (NoMethodError)

**Comment by isene** [comment]
With the latest updates, I fixed several small hicups with GTO/XEQ and other bits. I have the following code sort of running, but the answer is wrong. Could you walk through and check what's off?

```
01 LBL "A-R"
02 " "      
03 LBL 01
04 E3
05 X>Y?
06 GTO 00
07 -
08 "|M"   
09 GTO 01
10 LBL 00          
11 CLX
12 900
13 X<=Y?
14 "|CM" 
15 X>Y?
16 CLX
17 -
18 500
19 X<=Y?     
20 "|D"   
21 X>Y?
22 CLX
23 -
24 400
25 X<=Y?
26 "|CD"   
27 X>Y?
28 CLX
29 -
30 LBL 02          
31 E2
32 X>Y?
33 GTO 00    
34 -
35 "|C"   
36 GTO 02
37 LBL 00          
38 CLX     
39 90
40 X<=Y?
41 "|XC" 
42 X>Y?
43 CLX
44 -
45 50
46 X<=Y?
47 "|L"   
48 X>Y?
49 CLX
50 -
51 40
52 X<=Y?
53 "|XL"  
54 X>Y?
55 CLX
56 -
57 LBL 03          
58 10
59 X>Y?
60 GTO 00
61 -
62 "|X"
63 GTO 03    
64 LBL 00
65 DSE X
66 X<=Y?
67 "|IX" 
68 X>Y?
69 CLX
70 -
71 5
72 X<=Y?
73 "|V"
74 X>Y?
75 CLX
76 -     
77 4
78 X<=Y?
79 "|IV"   
80 X>Y?
81 CLX
82 -
83 LBL 04
84 1
85 X>Y?
86 GTO 00    
87 -
88 "|I"  
89 GTO 04
90 LBL 00
91 AVIEW
92 END

```

**Comment by acser123** [comment]
What number did you try to convert from Arabic to Roman numerals?

    On Monday, April 11, 2022, 08:34:11 AM EDT, Geir Isene ***@***.***> wrote:  
 
 


With the latest updates, I fixed several small hicups with GTO/XEQ and other bits. I have the following code sort of running, but the answer is wrong. Could you walk through and check what's off?
01 LBL "A-R"
02 " "      
03 LBL 01
04 E3
05 X>Y?
06 GTO 00
07 -
08 "|M"   
09 GTO 01
10 LBL 00          
11 CLX
12 900
13 X<=Y?
14 "|CM" 
15 X>Y?
16 CLX
17 -
18 500
19 X<=Y?     
20 "|D"   
21 X>Y?
22 CLX
23 -
24 400
25 X<=Y?
26 "|CD"   
27 X>Y?
28 CLX
29 -
30 LBL 02          
31 E2
32 X>Y?
33 GTO 00    
34 -
35 "|C"   
36 GTO 02
37 LBL 00          
38 CLX     
39 90
40 X<=Y?
41 "|XC" 
42 X>Y?
43 CLX
44 -
45 50
46 X<=Y?
47 "|L"   
48 X>Y?
49 CLX
50 -
51 40
52 X<=Y?
53 "|XL"  
54 X>Y?
55 CLX
56 -
57 LBL 03          
58 10
59 X>Y?
60 GTO 00
61 -
62 "|X"
63 GTO 03    
64 LBL 00
65 DSE X
66 X<=Y?
67 "|IX" 
68 X>Y?
69 CLX
70 -
71 5
72 X<=Y?
73 "|V"
74 X>Y?
75 CLX
76 -     
77 4
78 X<=Y?
79 "|IV"   
80 X>Y?
81 CLX
82 -
83 LBL 04
84 1
85 X>Y?
86 GTO 00    
87 -
88 "|I"  
89 GTO 04
90 LBL 00
91 AVIEW
92 END

**Comment by isene** [comment]
I try to convert 14 and get this:

`       VIV   I  I  I  I  I`

**Comment by acser123** [comment]
Your code has "|C" instead of "|-C" (append C)

This code segment -- for the first time and without modifications from what did not work before -- now works for me.
$ xrpn -l ar4.hp41 
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> 3212 
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 3,212.0000   L = 0.0000
> xeq "A-R"
 MMMCCXII
------------------------------
T = 0.0000   α =  MMMCCXII
Z = 0.0000
Y = 0.0000
X = 1.0000   L = 0.0000
> 3892
------------------------------
T = 0.0000   α =  MMMCCXII
Z = 0.0000
Y = 1.0000
X = 3,892.0000   L = 1.0000
> xeq "A-R"
 MMMDCCCXCII
------------------------------
T = 0.0000   α =  MMMDCCCXCII
Z = 1.0000
Y = 0.0000
X = 1.0000   L = 0.0000
> 

$ cat ar4.hp41 
LBL "A-R"
" "
LBL 01
E3
X>Y?
GTO 00
-
"|-M"
GTO 01
LBL 00
clx
900
X<=Y?
"|-CM"
X>Y?
CLX
-
500
X<=Y?
"|-D"
X>Y?
CLX
-
400
X<=Y?
"|-CD"
X>Y?
CLX
-
LBL 02
E2
X>Y?
GTO 00
-
"|-C"
GTO 02
LBL 00
clx
90
X<=Y?
"|-XC"
X>Y?
CLX
-
50
X<=Y?
"|-L"
X>Y?
CLX
-
40
X<=Y?
"|-XL"
X>Y?
CLX
-
LBL 03
10
X>Y?
GTO 00
-
"|-X"
GTO 03
LBL 00
DSE X
X<=Y?
"|-IX"
X>Y?
CLX
-
5
X<=Y?
"|-V"
X>Y?
CLX
-
4
X<=Y?
"|-IV"
X>Y?
CLX
-
LBL 04
1
X>Y?
GTO 00
-
"|-I"
GTO 04
LBL 00
AVIEW
END
$

**Comment by acser123** [comment]
I verified that your listing also worked for me. If you can verify that it works for you, then I am OK with you closing this bug :) 
Thanks.

**Comment by isene** [comment]
I have no idea how you manage to get that to work. I can't. Need to do some more debugging before I close this issue.
