### ISSUE TITLE
EOU: When loading a program with -l or --load, it should be the default, to be run page

### ISSUE THREAD

**Issue by acser123** [isene/xrpn#21]
When you load a program using xrpn -l the program's global label should be the default label to use with XEQ, without having to do a page 1. This saves a step in debugging and running programs.

**Comment by isene** [comment]
I don't want to do this as I want to open up the possibility of loading several programs at once, each file to a different page.

**Comment by isene** [comment]
I decided to do this anyway.

Also added the possibility to save and load a state in Debug Mode - and to load a full state when running XRPN with the -s or --state switch.

**Comment by acser123** [comment]
Excellent, thanks.     On Wednesday, April 13, 2022, 04:02:31 AM EDT, Geir Isene ***@***.***> wrote:  
 
 


I decided to do this anyway.

Also added the possibility to save and load a state in Debug Mode - and to load a full state when running XRPN with the -s or --state switch.
