### ISSUE TITLE
acos should check for the domain of its argument and not cause a crash

### ISSUE THREAD

**Issue by acser123** [isene/xrpn#22]
Using http://hp41programs.yolasite.com/geodesic2.php 1) TGD.

$ xrpn -l tgd.hp41 
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> page 1
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> xeq "TGD"
Traceback (most recent call last):
	2: from /home/acser/bin/xrpn:62:in `<main>'
	1: from /home/acser/.xrpn/cmd/acos:4:in `acos'
/home/acser/.xrpn/cmd/acos:4:in `acos': Numerical argument is out of domain - "acos" (Math::DomainError)
$ 

t2.hp41    tgd.hp41
$ cat tgd.hp41
LBL "TGD"
DEG
HR
STO 14
RDN
HR
14.929
STO 11
+
STO 13
RDN
HR
STO 12
X<>Y
HR
ST+ 11
6378.172
STO 01
.07
-
STO 02
21.349686
-
STO 03
RCL 11
RCL 12
XEQ 01
STO 05
RCL 09
STO 06
RCL 10
STO 07
RCL 13
ST- 11
RCL 14
XEQ 01
XEQ 00
STO 04
RCL 01
ST/ 05
ST/ 08
RCL 02
ST+ 01
ST/ 06
ST/ 09
RCL 03
ST/ 07
ST/ 10
RCL 08
sqr
RCL 09
sqr
RCL 10
sqr
+
+
STO 13
RCL 05
sqr
RCL 06
sqr
RCL 07
sqr
+
+
STO 00
-
RCL 04
ACOS
STO 02
SIN
STO 15
*
RCL 08
XEQ 00
ST+ X
STO 09
RCL 00
RCL 13
+	 
RCL 04
*
-
X#0?
/
ATAN
STO 08
2
ST/ 01
ST/ 11
/
STO 05
XEQ 02
STO 06
RCL 05
90
+
XEQ 02
STO 07
RCL 02
D-R
RCL 08
COS
STO 05
sqr
ST+ X
RCL 04
RCL 15
ST* 05
*
ST* Y
-
-
4
/
RCL 06
ST/ 15
RCL 07
ST- Y
ST+ X	
/
STO 07
*
RCL 05
-
+
RCL 07
*
+
ST* 15
RCL 14
ENTER
GTO 03
LBL 00
RCL 05
*
RCL 09
RCL 06
*
+
RCL 10
RCL 07
*
+
RTN
LBL 01
1
p_r
X<>Y
RCL 03
sqr
*
STO 10
RDN
p_r
RCL 01
sqr
*
STO Z
sqr	
X<>Y
RCL 02
sqr
*
STO 09
sqr
RCL 10
sqr
+
+
SQRT
ST/ 09
ST/ 10
/
STO 08
RTN
LBL 02
RCL 02
2
/
+
ENTER
SIN
ENTER
sqr
RCL 13
*
RCL 02
R^
-
SIN
ST* Z
sqr
RCL 00          
*
+
X<>Y
RCL 09
*
+
END

**Comment by isene** [comment]
Fixed it - but not sure what to actually do with such errors. It now ignors them and simply prints out an error message...

**Comment by acser123** [comment]
This is not working as expected. It seems that there is a new bug here: enter 151.12178 onto the stack you get 112178...
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 3.6812e-19
X = 3.0000   L = 3.6812e-19
> 151.12178  
------------------------------
T = 0.0000   α = 
Z = 3.6812e-19
Y = 3.0000
X = 112,178.0000   L = 3.0000
>
