### ISSUE TITLE
@line in xrpn intermittently gets no or incorrect value

### ISSUE THREAD

**Issue by acser123** [isene/xrpn#23]
Adding  the following lines

    ### Debug
    puts "l1=#{l1}"
    puts "l2=#{l2}"
    puts "l3=#{l3}"

 before the line where xrpn crashes 

if not ($cmd.include?(l1.downcase) or l1.match(/^-*[\d\.,]+$/) or l1.match(/^".*/) ) # Catch unknown command

Debug printing out of l1, l2 and l3 reveals that the current line into @line intermittently fails and produces and emty string.

X = 543.0000   L = 1.0000
> xeq "A-R"
l1=xeq
l2="A-R"
l3=
l1=lbl
l2=01
l3=
l1=xgty?
l2=
l3=
l1=gto
l2=00
l3=
l1=clx
l2=
l3=
l1= <<< This is the problem right here.  This happens with numbers only apparently.
l2=
l3=
Traceback (most recent call last):
/home/acser/bin/xrpn:61:in `<main>': undefined method `downcase' for nil:NilClass (NoMethodError)
$

**Comment by isene** [comment]
This seems to be fixed now - but there is a serious stack-lift-disable bug in the code that I will attack tomorrow.

Can I close this one?

**Comment by acser123** [comment]
Can't reproduce any more.
