### ISSUE TITLE
XEQ nn (local label) and RTN does not work reliably

### ISSUE THREAD

**Issue by acser123** [isene/xrpn#24]
First program on 
http://hp41programs.yolasite.com/geodesic2.php

$ xrpn -l tgd.hp41 
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> 151.12178
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 151.1218   L = 0.0000
> -33.51411
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 151.1218
X = -33.5141   L = 151.1218
> -116.51504
------------------------------
T = 0.0000   α = 
Z = 151.1218
Y = -33.5141
X = -116.5150   L = -33.5141
> 33.21224
------------------------------
T = 151.1218   α = 
Z = -33.5141
Y = -116.5150
X = 33.2122   L = -116.5150
> xeq "TGD"
Error: No such label: 03
------------------------------
T = 33.3562   α = 
Z = 33.3562
Y = 33.3562
X = 31.5196   L = -0.0000
> l
Line 145: rtn
------------------------------
T = 33.3562   α = 
Z = 33.3562
Y = 33.3562
X = 31.5196   L = -0.0000

> pprgx
01◆lbl "TGD"
02 deg
03 hr
04 sto 14
05 rdn
06 hr
07 14.929
08 sto 11
09 +
10 sto 13
11 rdn
12 hr
13 sto 12
14 xy
15 hr
16 stplus 11
17 6378.172
18 sto 01
19 .07
20 -
21 sto 02
22 21.349686
23 -
24 sto 03
25 rcl 11
26 rcl 12
27 xeq 01
28 sto 05
29 rcl 09
30 sto 06
31 rcl 10
32 sto 07
33 rcl 13
34 stsubtract 11
35 rcl 14
36 xeq 01
37 xeq 00
38 sto 04
39 rcl 01
40 stdivide 05
41 stdivide 08
42 rcl 02
43 stplus 01
44 stdivide 06
45 stdivide 09
46 rcl 03
47 stdivide 07
48 stdivide 10
49 rcl 08
50 sqr
51 rcl 09
52 sqr
53 rcl 10
54 sqr
55 +
56 +
57 sto 13
58 rcl 05
59 sqr
60 rcl 06
61 sqr
62 rcl 07
63 sqr
64 +
65 +
66 sto 00
67 -
68 rcl 04
69 acos
70 sto 02
71 sin
72 sto 15
73 *
74 rcl 08
75 xeq 00
76 stplus X
77 sto 09
78 rcl 00
79 rcl 13
80 +	 
81 rcl 04
82 *
83 -
84 xneq0?
85 /
86 atan
87 sto 08
88 2
89 stdivide 01
90 stdivide 11
91 /
92 sto 05
93 xeq 02
94 sto 06
95 rcl 05
96 90
97 +
98 xeq 02
99 sto 07
100 rcl 02
101 d_r
102 rcl 08
103 cos
104 sto 05
105 sqr
106 stplus X
107 rcl 04
108 rcl 15
109 stmultiply 05
110 *
111 stmultiply Y
112 -
113 -
114 4
115 /
116 rcl 06
117 stdivide 15
118 rcl 07
119 stsubtract Y
120 stplus X
121 /
122 sto 07
123 *
124 rcl 05
125 -
126 +
127 rcl 07
128 *
129 +
130 stmultiply 15
131 rcl 14
132 enter
133 gto 03
134◆lbl 00
135 rcl 05
136 *
137 rcl 09
138 rcl 06
139 *
140 +
141 rcl 10
142 rcl 07
143 *
144 +
145 rtn
146◆lbl 01
147 1
148 p_r
149 xy
150 rcl 03
151 sqr
152 *
153 sto 10
154 rdn
155 p_r
156 rcl 01
157 sqr
158 *
159 sto z
160 sqr	
161 xy
162 rcl 02
163 sqr
164 *
165 sto 09
166 sqr
167 rcl 10
168 sqr
169 +
170 +
171 sqrt
172 stdivide 09
173 stdivide 10
174 /
175 sto 08
176 rtn
177◆lbl 02
178 rcl 02
179 2
180 /
181 +
182 enter
183 sin
184 enter
185 sqr
186 rcl 13
187 *
188 rcl 02
189 rup
190 -
191 sin
192 stmultiply Z
193 sqr
194 rcl 00
195 *
196 +
197 xy
198 rcl 09
199 *
200 +
201 end

**Comment by acser123** [comment]
xeq 00 on lines 37 and 75 followed by RTN may cause this problem.

**Comment by acser123** [comment]
Another issue: XEQ alters stack contents without any instructions:

Line 26: rcl 12
------------------------------
T = 151.2050   α = 
Z = 6,356.7523
Y = 166.1340
X = -33.8614   L = 166.1340
> s
Line 27: xeq 01
------------------------------
T = -32,796,658.3222   α = 
Z = -32,796,658.3222
Y = -32,796,658.3222
X = -0.8079   L = 40,596,553.2604

**Comment by acser123** [comment]
$ xrpn -l tgd.hp41 
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> page 1
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> s
Line 2: deg
deg
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> s
Line 3: hr
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> s
Line 4: sto 14
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> s
Line 5: rdn
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> s
Line 6: hr
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> s
Line 7: 14.929
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 14.9290   L = 0.0000
> s
Line 8: sto 11
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 14.9290   L = 0.0000
> s
Line 9: +
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 14.9290   L = 14.9290
> s
Line 10: sto 13
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 14.9290   L = 14.9290
> s
Line 11: rdn
------------------------------
T = 14.9290   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 14.9290
> s
Line 12: hr
------------------------------
T = 14.9290   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> s
Line 13: sto 12
------------------------------
T = 14.9290   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> s
Line 14: xy
------------------------------
T = 14.9290   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> s
Line 15: hr
------------------------------
T = 14.9290   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> s
Line 16: stplus 11
------------------------------
T = 14.9290   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> s
Line 17: 6378.172
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 6,378.1720   L = 0.0000
> s
Line 18: sto 01
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 6,378.1720   L = 0.0000
> s
Line 19: .07
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 6,378.1720
X = 0.0700   L = 6,378.1720
> s
Line 20: -
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 6,378.1020   L = 0.0700
> s
Line 21: sto 02
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 6,378.1020   L = 0.0700
> s
Line 22: 21.349686
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 6,378.1020
X = 21.3497   L = 6,378.1020
> s
Line 23: -
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 6,356.7523   L = 21.3497
> s
Line 24: sto 03
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 6,356.7523   L = 21.3497
> s
Line 25: rcl 11
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 6,356.7523
X = 14.9290   L = 6,356.7523
> s
Line 26: rcl 12
------------------------------
T = 0.0000   α = 
Z = 6,356.7523
Y = 14.9290
X = 0.0000   L = 14.9290
> s
Line 27: xeq 01
------------------------------
T = 39,307,921.1802   α = 
Z = 39,307,921.1802
Y = 39,307,921.1802
X = 0.9662   L = 40,681,018.7987
> p
Line 175: sto 08
------------------------------
T = 39,307,921.1802   α = 
Z = 39,307,921.1802
Y = 39,307,921.1802
X = 0.9662   L = 40,681,018.7987
> s
Line 177: lbl 02
------------------------------
T = 39,307,921.1802   α = 
Z = 39,307,921.1802
Y = 39,307,921.1802
X = 0.9662   L = 40,681,018.7987
>

**Comment by isene** [comment]
There is no LBL 03 in the code...

**Comment by acser123** [comment]
Looks like this is synthetic programming, which is outside the scope of XRPN. Closing this issue.
