### ISSUE TITLE
Can't place a long decimal fraction on the stack

### ISSUE THREAD

**Issue by acser123** [isene/xrpn#25]
$ xrpn
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> 151.12178
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 112,178.0000   L = 0.0000 <<<<<<<<<<<<<<<---- This is the problem.
> fix 6
------------------------------
T = 0.000000   α = 
Z = 0.000000
Y = 0.000000
X = 112,178.000000   L = 0.000000
> 151.12178
------------------------------
T = 0.000000   α = 
Z = 0.000000
Y = 112,178.000000
X = 112,178.000000   L = 112,178.000000
>

**Comment by isene** [comment]
Fixed by latest update.
