### ISSUE TITLE
Importing code with line numbers does not work consistently

### ISSUE THREAD

**Issue by acser123** [isene/xrpn#26]
From https://www.hpmuseum.org/software/41td/rtloc1.htm

> pprg
01◆lbl "ROOTS1"
02  02 "Z1?"
03  03 PROMPT
04  04 STO 01
05  05 "Z2?"
06  06 PROMPT
07  07 STO 02
08  08 "P1?"
09  09 PROMPT
10  10 STO 03
11  11 "P2?"
12  12 PROMPT
13  13 STO 04
14  14 "P3?"
15  15 PROMPT
16  16 STO 05
17  17 "P4?"
18  18 PROMPT
19  19 STO 06
20◆ 20 LBL A
21  21 "a?"
22  22 PROMPT
23  23 "W?"
24  24 PROMPT
25◆ 25 LBL B
26  26 STO 08
27  27 xy
28  28 STO 07
29  29 r_p
30  30 RCL 06
31  31 XEQ E
32  32 RCL 05
33  33 XEQ E
34  34 RCL 04
35  35 XEQ E
36  36 RCL 03
37  37 XEQ E
38  38 RCL 02
39  39 XEQ D
40  40 RCL 01
41  41 XEQ D
42  42 xy
43  43 STO 00
44  44 180
45  45 -
46  46 ABS
47  47 .01
48  48 xgty?
49  49 GTO C
50  50 RCL 00
51  51 60
52  52 /
53  53 4
54  54 -
55  55 CHS
56  56 RCL 08
57  57 *
58  58 STO 08
59  59 RCL 07
60  60 RCL 08
61  61 GTO B
62◆ 62 LBL C
63  63 RCL Z
64  64 "K="
65  65 XEQ d
66  66 RCL 08
67  67 "W="
68  68 XEQ d
69  69 GTO A
70◆ 70 LBL d
71  71 FIX 03
72  72 ARCL X
73  73 AVIEW
74  74 STOP
75  75 RTN
76  76 STOP
77◆ 77 LBL E
78  78 RCL 07
79  79 +
80  80 RCL 08
81  81 xy
82  82 r_p
83  83 xy
84  84 RDN
85  85 *
86  86 RDN
87  87 +
88  88 rup
89  89 RTN
90◆ 90 LBL D
91  91 RCL 07
92  92 +
93  93 RCL 08
94  94 xy
95  95 r_p
96  96 xy
97  97 RDN
98  98 /
99  99 RDN
100 -
101 chs
102 rup
103 rtn
104 rcl 08
105 stop
106 end

$ cat roots1.hp41 
01 LBL "ROOTS1"
 02 "Z1?"
 03 PROMPT
 04 STO 01
 05 "Z2?"
 06 PROMPT
 07 STO 02
 08 "P1?"
 09 PROMPT
 10 STO 03
 11 "P2?"
 12 PROMPT
 13 STO 04
 14 "P3?"
 15 PROMPT
 16 STO 05
 17 "P4?"
 18 PROMPT
 19 STO 06
 20 LBL A
 21 "a?"
 22 PROMPT
 23 "W?"
 24 PROMPT
 25 LBL B
 26 STO 08
 27 X<>Y
 28 STO 07
 29 R-P
 30 RCL 06
 31 XEQ E
 32 RCL 05
 33 XEQ E
 34 RCL 04
 35 XEQ E
 36 RCL 03
 37 XEQ E
 38 RCL 02
 39 XEQ D
 40 RCL 01
 41 XEQ D
 42 X<>Y
 43 STO 00
 44 180
 45 -
 46 ABS
 47 .01
 48 X>Y?
 49 GTO C
 50 RCL 00
 51 60
 52 /
 53 4
 54 -
 55 CHS
 56 RCL 08
 57 *
 58 STO 08
 59 RCL 07
 60 RCL 08
 61 GTO B
 62 LBL C
 63 RCL Z
 64 "K="
 65 XEQ d
 66 RCL 08
 67 "W="
 68 XEQ d
 69 GTO A
 70 LBL d
 71 FIX 03
 72 ARCL X
 73 AVIEW
 74 STOP
 75 RTN
 76 STOP
 77 LBL E
 78 RCL 07
 79 +
 80 RCL 08
 81 X<>Y
 82 R-P
 83 X<>Y
 84 RDN
 85 *
 86 RDN
 87 +
 88 R^
 89 RTN
 90 LBL D
 91 RCL 07
 92 +
 93 RCL 08
 94 X<>Y
 95 R-P
 96 X<>Y
 97 RDN
 98 /
 99 RDN
100 -
101 CHS
102 R^
103 RTN
104 RCL 08
105 STOP
106 END
$

**Comment by isene** [comment]
This is because the lines have a space in front of the line numbers. In any case, I added a stripping of spaces or tabs in front of line numbers. 

BTW; Check the docs for latest features.
