### ISSUE TITLE
deg 9 sin cos tan atan acos asin does not return 9, goes to 8

### ISSUE THREAD

**Issue by acser123** [isene/xrpn#29]
This is an old trick to test the accuracy of a calculator. This does not work on XRPN.

$ xrpn
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> deg
deg
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> 9
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 9.0000   L = 0.0000
> sin
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.1564   L = 9.0000
> cos
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.1564
> tan
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0175   L = 0.0000
> atan
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0175
> acos
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.1564   L = 0.0000
> asin
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 8.0000   L = 0.1564
>

**Comment by isene** [comment]
This is a really weird one. I will have to dig on this a bit later today.

**Comment by acser123** [comment]
May have to do with rounding….

**Comment by isene** [comment]
Found it! Tricky and fun to hunt down :)
