### ISSUE TITLE
Ease-of-use (EOU) request: implement robust cleansing and parsing of FOCAL source listings for -f and other load operations

### ISSUE THREAD

**Issue by acser123** [isene/xrpn#4]
This EOU request is a collection of things that would make XRPN the tool of choice when developing, and especially reusing existing FOCAL code and libraries. The more XRPN can read formats from other emulators OOTB without user efforts, the more popular it will be.

When loading the source file with -f and -l flags, implement parsing of every line and stop loading with an error message as to which line offends syntax (no such command on line xxx, or something similar).

Recommend looking at https://github.com/whitequark/parser for a starting point.

Part of this request would be to deal with the following in xrpn (adding to the list as I see more code out there):

1) remove any trailing whitespaces from listings before reading in commands 
>>> Partially done. Still there are some bugs around it.  See issue #31 

2) remove any line numbers and whitespaces, tabs, etc. in front of commands
>>> Partially done. Still there are some bugs around it. See issue #32 

3) remove any special characters (such as <Ctrl>+I, etc.) that are created in vi/vim or editors as a result of pasting programs from web pages esp http://hp41programs.yolasite.com/ where one of the kings of HP 41 programming, Jean-Marc Baillard publishes his new (!) HP 41 programs.

>>> Partially done. Still there are some bugs around it. See issues #31 and #32.

4) Be able to use the email program listing format (has its own quirks) that comes straight out of +i41CX from iOS (one of the best emulators). There are a few minor differences, such as the append character operation: 
XRPN: "|-ABC"
+i41CX: >"ABC"

>>> Implemented correctly. Thank you :)

5) Port http://www.hpmuseum.org/software/hp41uc.zip
  or  https://sourceforge.net/p/hp41uc/code/ci/master/tree/Win32App_x86/Win32App_x86.zip?format=raw to simple Ruby based text parsers and converters to allow for importing .raw programs.

>>> Opened separate EOU #33  for this.

**Comment by isene** [comment]
Added the +i41CX style with >"ABC" for appending to Alpha in the latest update. Will work on the rest later.

**Comment by isene** [comment]
BTW; Spaces/tabs preceding or trailing commands are already taken care of.

**Comment by isene** [comment]
Also, the XRPN way of appending is either "|-ABC" or simply "|ABC"

**Comment by isene** [comment]
So, 1-5 should be OK. Do you have the specification for the RAW format somewhere?

**Comment by acser123** [comment]
This is the closest thing I found: https://www.hpmuseum.org/software/41uc.htm
    On Thursday, April 14, 2022, 09:36:32 AM EDT, Geir Isene ***@***.***> wrote:  
 
 


So, 1-5 should be OK. Do you have the specification for the RAW format somewhere?

**Comment by acser123** [comment]
Reading this program does not work (2 in the above list)

$ cat mnode.hp41 
 01  LBL "MNODE"
  02  DEG
  03  XEQ "J0"
  04  13.6061104
  05  STO 03
  06  /
  07  INT 
  08  STO 04
  09  331.73736
  10  *
  11  7.28
  12  +
  13  STO 02
  14  ST+ X
  15  RCL 04
  16  177.76374
  17  *
  18  38.38
  19  +
  20  STO 00
  21  -
  22  SIN
  23  RCL 00
  24  SIN
  25  472
  26  *
  27  -
  28  RCL 00	  
  29  RCL 02
  30  -
  31  SIN
  32  87
  33  *
  34  +
  35  RCL 00          
  36  RCL 02
  37  +
  38  SIN
  39  RCL 04
  40  13.4102
  41  *
  42  17.4
  43  +
  44  STO 01
  45  RCL 02
  46  -
  47  SIN
  48  +
  49  8
  50  *
  51  +
  52  RCL 00
  53  RCL 01
  54  +
  55  RCL 02
  56  -	  
  57  SIN
  58  4
  59  *
  60  +
  61  RCL 00
  62  ST+ X
  63  SIN
  64  LASTX
  65  RCL 02          
  66  -
  67  SIN
  68  +
  69  RCL 01
  70  RCL 02
  71  +
  72  SIN
  73  +
  74  RCL 01
  75  RCL 00
  76  -
  77  SIN
  78  +
  79  RCL 01
  80  SIN
  81  +
  82  RCL 02
  83  ST+ X
  84  SIN	  
  85  +
  86  RCL 02
  87  SIN
  88  55
  89  *
  90  -
  91  3
  92  *
  93  +
  94  RCL 00          
  95  RCL 01
  96  +
  97  SIN
  98  RCL 02
  99  2
100  /
101  SIN
102  -
103  RCL 04
104  .72
105  *
106  56
107  +
108  SIN
109  +
110  ST+ X
111  +
112  20662	
113  +
114   E3
115  /
116  RCL 03
117  RCL 04
118  *
119  +
120  INT
121  LASTX          
122  FRC
123  X<0?
124  DSE Y
125  FRC
126  24
127  ST* Y
128  MOD
129  HMS
130  X<>Y
131  XEQ "DT"
132  RCL 04
133  2
134  MOD
135  X>0?
136  CHS
137  X=0?
138  SIGN
139  END
$ xrpn -l mnode.hp41
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> l
Line 1:  01  LBL "MNODE"
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> s
Line 2:   02  DEG
No such command: 02
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> 

From http://hp41programs.yolasite.com/moonnodes.php

**Comment by acser123** [comment]
Raw format: This is the closest thing I found: https://www.hpmuseum.org/software/41uc.htm

**Comment by isene** [comment]
That is some horrible documentation. I will do some work on that tomorrow.

Check latest. I got http://hp41programs.yolasite.com/moonnodes.php to read.

**Comment by isene** [comment]
Couldn't sleep. Did the work on the various import formats in that link. Please verify that this issue can be closed :)

**Comment by acser123** [comment]
Many thanks :) I will do this.
    On Thursday, April 14, 2022, 08:40:42 PM EDT, Geir Isene ***@***.***> wrote:  
 
 


Couldn't sleep. Did the work on the various import formats in that link. Please verify that this issue can be closed :)

**Comment by acser123** [comment]
4. Various alpha append commands work fine :)))
Thank you.

$ xrpn -l app.hp41 
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> l
Line 1: lbl "APP"
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> s
Line 2: "A"
------------------------------
T = 0.0000   α = A
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> s
Line 3: "|-B"
------------------------------
T = 0.0000   α = AB
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> s
Line 4: "|C"
------------------------------
T = 0.0000   α = ABC
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> s
Line 5: >"D"
------------------------------
T = 0.0000   α = ABCD
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> q   
$ cat app.hp41 
lbl "APP"
"A"
"|-B"
"|C"
>"D"
END
$

**Comment by acser123** [comment]
Thanks for all your work on these :)
