### ISSUE TITLE
xeq still does not work reliably

### ISSUE THREAD

**Issue by acser123** [isene/xrpn#5]
$ cat area.hp41
LBL "AREA"
2
xy
pow
pi
*
rtn
end
$ xrpn -f area.hp41
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 3.1416   L = 3.1416
> xeq "AREA"
[]
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 27.7245   L = 3.1416
> xeq "AREA"
[]
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 696,709,328.4073   L = 3.1416
>

**Comment by isene** [comment]
Remember that `pow` is Y^X and not X^Y.

**Comment by acser123** [comment]
Apologies.
