### ISSUE TITLE
pprg and ppgrx broken with --load or -l switch

### ISSUE THREAD

**Issue by acser123** [isene/xrpn#7]
$ xrpn -l area.hp41
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> pprgx
01◆lbl "XRPN"
02 end
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> pprg
01◆lbl "XRPN"
02 end
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> q
$ cat area.hp41
LBL "AREA"
2
pow
pi
*
rtn
end

**Comment by isene** [comment]
The program is loaded into page 1 (use pcat to see which programs are in which pages, and use `page 1` to switch to page 1 before you print the program in that page). Will add this to the Readme file.
