### ISSUE TITLE
Append character missing/not found

### ISSUE THREAD

**Issue by acser123** [isene/xrpn#8]
Not sure if the append character is implemented somehow. I could not find it. If it is, can you please document it. 

 The glyph at code point 127 (⊦) is called APPEND character in Hewlett-Packard terminology. In the HP-41C/CV/CX and HP-42S series of calculators, it is used to indicate that the following characters will be appended to the alpha register rather than replacing the existing contents of the register.

from 
https://en.wikipedia.org/wiki/FOCAL_character_set

**Comment by isene** [comment]
Added to the documentations: To append characters to the Alpha register, start the string with a pipe (|) or a pipe and a minus (|-) as this mimics the "append character" of the HP-41.
